//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public int idJugador { get; set; }
        public string email { get; set; }
        public string nickname { get; set; }
        public string passwordHash { get; set; }
        public string passwordSalt { get; set; }
        public System.DateTime fecNacimiento { get; set; }
        public string genero { get; set; }
        public string paisResidencia { get; set; }
        public string fecUltimaConexion { get; set; }
        public string timeZone { get; set; }
    }
}
